kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: flask
  namespace: default
spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: 'flask:latest'
  resources: {}
  successfulBuildsHistoryLimit: 5
  failedBuildsHistoryLimit: 5
  strategy:
    type: Docker
    dockerStrategy:
      from:
        kind: ImageStreamTag
        namespace: openshift
        name: 'python:3.8'
  postCommit: {}
  source:
    type: Git
    git:
      uri: 'https://github.com/mtsecoelho/flask.git'
    contextDir: /
  runPolicy: Serial
