kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  name: flask
  namespace: default
spec:
  lookupPolicy:
    local: false
  tags:
    - name: latest
      annotations: null
      from:
        kind: DockerImage
        name: 'openshift/python:3.8'
      generation: 5
      importPolicy:
        importMode: Legacy
      referencePolicy:
        type: Source